name: Deploy to GitHub Pages

on:
  push:
    branches: [master]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      my_secret: ${{secrets.ACCESS_TOKEN}}

    steps:
      - uses: actions/checkout@v4.1.0
      - uses: subosito/flutter-action@v2.11.0
        with:
          flutter-version: "3.16.0"
          channel: 'stable'

      - run: flutter clean
      - run: flutter pub get
      - uses: bluefireteam/flutter-gh-pages@v8
        with:
         baseHref: /pixartmaker/